### ISSUE TITLE
bootstrap 4.1.2 support

### ISSUE THREAD

**Issue by vinaylakkam** [seanCodes/bootstrap-less-port#11]
Seems bootstrap <4.1.1 has security vulnerabilities. Would you please make it aligned with bootstrap 4.1.2

**Comment by carlo-13** [comment]
Hi.

Bootstrap v4.1.3 was realise recently, it would be great to update the package 😉

**Comment by calvinjuarez** [comment]
@seanCodes dibs.

**Comment by seanCodes** [comment]
Finally got some time to get this updated (thanks for pinging me @calvinjuarez)

- [v0.5.0](https://github.com/seanCodes/bootstrap-less-port/tree/v0.5.0) aligns with Bootstrap 4.1.3 (the latest)
- [v0.4.0](https://github.com/seanCodes/bootstrap-less-port/tree/v0.4.0) aligns with Bootstrap 4.1.2 (in case anyone needs it)

Thanks everyone for your patience!

**Comment by carlo-13** [comment]
Thank you!
