### ISSUE TITLE
Cannot find module while using Parcel bundler

### ISSUE THREAD

**Issue by mirkea** [seanCodes/bootstrap-less-port#16]
I have a simple .less file that contains
```
@import "../../node_modules/bootstrap-less-port/less/_mixins";
@import "../../node_modules/bootstrap-less-port/less/_functions";
```
and I get errors such as 
>Cannot find module './plugins/theme-color-level' from '<PROJECT_PATH>/node_modules/bootstrap-less-port/less'

I tried tweaking around with those files and it looks like adding ".js" when mentioning plugin paths fixes the issue. For example
>@plugin "../plugins/breakpoints";

would cause an error while

>@plugin "../plugins/breakpoints.js"; 

would work.

**Comment by seanCodes** [comment]
Thanks for reporting this! Out of curiosity, what version of Less are you using?

**Comment by mirkea** [comment]
3.9.0

**Comment by melissa-murphy** [comment]
I have had this issue as well, but with sass - everything I read pointed back to a bundling issue with Parcel, so this issue is very possibly not this Bootstrap port. :)
