### ISSUE TITLE
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

### ISSUE THREAD

**Issue by MihaiSlujitoru** [seanCodes/bootstrap-less-port#18]
I installed bootstrap less port into my Vue project. I updated less to 3.9.0 and less-loader to 3.9.0 and 5.0.0 as well. 

Do you have any idea what's going on?  

```
 error  in ./node_modules/bootstrap-less-port/less/bootstrap.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


//}
each(@form-validation-states, #(@data, @state) {
^
Error evaluating function `each`: Operation on an invalid type
      in /Users/mihai/code/Shaw-PhiladelphiaCommercial/pc-vue/node_modules/bootstrap-less-port/less/_forms.less (line 247, column 0)

 @ ./node_modules/bootstrap-less-port/less/bootstrap.less 4:14-190 14:3-18:5 15:22-198
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.14.70:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by MihaiSlujitoru** [comment]
When I move bootstrap-less-port from version 2.2.1 to 1.0.0 it does compile properly. 

I do use less 3.9.0

**Comment by cthrax** [comment]
I'm also seeing this in my angular 8 project with version 2.2.1.

**Comment by cthrax** [comment]
I think I've narrowed it down to this line. https://github.com/seanCodes/bootstrap-less-port/blob/master/less/mixins/_forms.less#L96 I'm not sure what is supposed to be going on there so I don't know how you can take a property of "center right <some value>" and divide it by "<some value> <some other value>" but I'm really not a less expert either.

**Comment by janwagner** [comment]
Same here for my react app

**Comment by janwagner** [comment]
Unfortunately for me "parens-division" does not fix the issue, or am I doing it wrong?

-  "less": "^3.10.0",
- "less-loader": "^5.0.0",

`{
    loader: 'less-loader',
        options: {
            parensDivision: true,
        }
}`

**Comment by janwagner** [comment]
ok, got it :)

`
loader: 'less-loader',
options: {
    math: {
        'parens-division': true,
    }
}`

**Comment by MihaiSlujitoru** [comment]
@seanCodes Yes, that works. Thx a bunch!

**Comment by cthrax** [comment]
For those following along at home, or find this via google. I have a fork that compiles with angular until either angular allows passing flags or less changes their default flags. Not likely to be well maintained, but it might save someone some time. https://github.com/cthrax/bootstrap-less-port

**Comment by seanCodes** [comment]
@cthrax Were minor changes required to make it work? I’d be happy to merge if you submit a PR

**Comment by cthrax** [comment]
@seanCodes pretty minor, pull-request linked.
