### ISSUE TITLE
Breaking change after setting node engine >= 15

### ISSUE THREAD

**Issue by adripanico** [seanCodes/bootstrap-less-port#29]
My build broke after [this commit](https://github.com/seanCodes/bootstrap-less-port/commit/e7c6eba99b881165a7b2b5653cbb63090f8a335f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) with the error

`error bootstrap-less-port@2.5.0: The engine "node" is incompatible with this module. Expected version ">=15". Got "10.17.0"
error Found incompatible module.`

I was importing this dependency as

`"bootstrap-less-port": "^2.3.1",`

Removing the caret (`^`) modifier solved the issue for me.

**Comment by seanCodes** [comment]
Sorry for the trouble, I’ll get this fixed this weekend.
