### ISSUE TITLE
#media-breakpoint-only

### ISSUE THREAD

**Issue by burgdigital-np** [seanCodes/bootstrap-less-port#3]
Hey,
is it possible that the breakpoint functions
#media-breakpoint-only
#media-breakpoint-between
are not working yet?

If I do:
.bd-header {
  #media-breakpoint-only(lg, {
    min-height: 120px;
  });
}
I get:
@media (max-width:1199.98px){.bd-header{min-height:120px}}

**Comment by seanCodes** [comment]
@burgdigital-np Yep, that's a bug! Thanks for reporting it! I'll get it fixed with asap. Should be out with the next version.
