### ISSUE TITLE
.custom-select appearance cross-browser

### ISSUE THREAD

**Issue by mageho** [seanCodes/bootstrap-less-port#5]
Good morning,

I noticed something while I was on Firefox Quantum 60.0.

The custom-select display the caret while on css bootstrap version not.
I just checked the css ouput of your less files and custom-select class doesn't have -webkit & -moz
prefix for comptability.

bootstrap-less-port/less/_custom-forms.less
ligne 181
```css
appearance: none;
```

the code is the same as scss version of bootstrap
[https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L180](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L180)

for reference, this is the line of the css version:
[https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L3598](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L3598)

Could you take a look and get back to me ?

Thank you,

Ilan PARMENTIER

**Comment by seanCodes** [comment]
@mageho Yes, this is correct. If you want your compiled CSS to include prefixes, you’ll need to handle that separately using a tool like Autoprefixer. You can see how that’s done in this repo by looking at the scripts in [package.json](https://github.com/seanCodes/bootstrap-less-port/blob/master/package.json#L33). First the code is compiled to CSS, then it’s run through Autoprefixer using the Post-CSS CLI tool.

Hopefully this helps! Let me know if you have any other questions and feel free to reopen if I missed something!
